CREATE TABLE scan_list (
	scan_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	project_name VARCHAR(16) NOT NULL,
	project_id INT UNSIGNED NOT NULL,
	scan_time INT UNSIGNED NOT NULL,
	scan_info VARCHAR(256) NOT NULL
	);

CREATE TABLE host_list (
	host_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	scan_id INT UNSIGNED NOT NULL,
	host_ip VARCHAR(16) NOT NULL,
	port_info TEXT NOT NULL
	);

CREATE TABLE port_list (
	port_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	scan_id INT UNSIGNED NOT NULL,
	host_id INT UNSIGNED NOT NULL,
	host_ip VARCHAR(16) NOT NULL,
	port_num SMALLINT UNSIGNED NOT NULL,
	service_name VARCHAR(256) NOT NULL,
	service_product VARCHAR(256) NOT NULL
	);